### ISSUE TITLE
The gitter link in README shows as missing picture

### ISSUE THREAD

**Issue by akauppi** [zalandoresearch/fashion-mnist#104]
<img width="360" alt="screen shot 2018-02-01 at 10 10 42" src="https://user-images.githubusercontent.com/1297734/35670262-5104d222-0738-11e8-8c93-f943db2d2766.png">

**Comment by hanxiao** [comment]
It is caused by reaching the requests limit of these badge service. You may find some badge images are broken if there are too many requests from your area hit the badge service in a short time.

For example, mine shows good at the same time.
![image](https://user-images.githubusercontent.com/2041322/35670382-bba9a09e-0738-11e8-909b-523f29420583.png)
